name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: npm install

      - name: Spellchecking
        run: npm test

      - name: Running specs
        run: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
