name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CI: true

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        channel: [stable, beta]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1

    - uses: UziTech/action-setup-atom@v1
      with:
        channel: ${{ matrix.channel }}

    - name: Atom version
      run: atom -v

    - name: APM version
      run: apm -v

    - name: Install dependencies
      run: apm install

    - name: Run linter & spellcheck
      run: npm test

    - name: Run tests
      run: atom --test spec
